"""create_impianti_tags_tables

Revision ID: 4bf948c5ed6b
Revises: df0e8b938e47
Create Date: 2026-03-01 11:57:07.118023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4bf948c5ed6b'
down_revision: Union[str, Sequence[str], None] = 'df0e8b938e47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('impianti',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codice', sa.String(length=50), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('formato', sa.String(length=100), nullable=True),
    sa.Column('indirizzo', sa.String(length=300), nullable=True),
    sa.Column('citta', sa.String(length=100), nullable=False),
    sa.Column('provincia', sa.String(length=5), nullable=True),
    sa.Column('cap', sa.String(length=10), nullable=True),
    sa.Column('latitudine', sa.Float(), nullable=True),
    sa.Column('longitudine', sa.Float(), nullable=True),
    sa.Column('proprietario', sa.String(length=200), nullable=True),
    sa.Column('illuminato', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('digitale', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('facce', sa.Integer(), server_default='1', nullable=False),
    sa.Column('stato', sa.String(length=20), server_default='attivo', nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_impianti_citta'), 'impianti', ['citta'], unique=False)
    op.create_index(op.f('ix_impianti_codice'), 'impianti', ['codice'], unique=True)
    op.create_index(op.f('ix_impianti_id'), 'impianti', ['id'], unique=False)
    op.create_index(op.f('ix_impianti_nome'), 'impianti', ['nome'], unique=False)
    op.create_index(op.f('ix_impianti_tipo'), 'impianti', ['tipo'], unique=False)
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('colore', sa.String(length=7), server_default='#2563eb', nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tags_id'), 'tags', ['id'], unique=False)
    op.create_index(op.f('ix_tags_nome'), 'tags', ['nome'], unique=True)
    op.create_table('impianto_tags',
    sa.Column('impianto_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['impianto_id'], ['impianti.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('impianto_id', 'tag_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('impianto_tags')
    op.drop_index(op.f('ix_tags_nome'), table_name='tags')
    op.drop_index(op.f('ix_tags_id'), table_name='tags')
    op.drop_table('tags')
    op.drop_index(op.f('ix_impianti_tipo'), table_name='impianti')
    op.drop_index(op.f('ix_impianti_nome'), table_name='impianti')
    op.drop_index(op.f('ix_impianti_id'), table_name='impianti')
    op.drop_index(op.f('ix_impianti_codice'), table_name='impianti')
    op.drop_index(op.f('ix_impianti_citta'), table_name='impianti')
    op.drop_table('impianti')
    # ### end Alembic commands ###
