"""add_foto_columns_rename_concessionario

Revision ID: 8d3385ebe1d2
Revises: 4bf948c5ed6b
Create Date: 2026-03-01 12:26:38.403638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d3385ebe1d2'
down_revision: Union[str, Sequence[str], None] = '4bf948c5ed6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('impianti', sa.Column('concessionario', sa.String(length=200), nullable=True))
    op.add_column('impianti', sa.Column('foto_giorno', sa.String(length=500), nullable=True))
    op.add_column('impianti', sa.Column('foto_notte', sa.String(length=500), nullable=True))
    op.add_column('impianti', sa.Column('foto_frontale', sa.String(length=500), nullable=True))
    op.add_column('impianti', sa.Column('foto_contesto', sa.String(length=500), nullable=True))
    op.alter_column('impianti', 'stato',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=30),
               existing_nullable=False,
               existing_server_default=sa.text("'attivo'::character varying"))
    op.drop_column('impianti', 'proprietario')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('impianti', sa.Column('proprietario', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.alter_column('impianti', 'stato',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'attivo'::character varying"))
    op.drop_column('impianti', 'foto_contesto')
    op.drop_column('impianti', 'foto_frontale')
    op.drop_column('impianti', 'foto_notte')
    op.drop_column('impianti', 'foto_giorno')
    op.drop_column('impianti', 'concessionario')
    # ### end Alembic commands ###
